# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Ian's Website"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Techniques in C++, JavaScript, Java, Python, Web, Vim, etc."

# Tagline near the site title
tagline: "Simplex Sigillum Veri"

# The subpath of your site, e.g. /blog, for generating urls
baseurl: ""

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://ianding.io"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: Posts
  url: /posts/
- text: Tags
  url: /tags/
- text: About
  url: /about/

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "Ian"
author_bio:
author_url:  "https://ianding.io"
author_location:
author_image:

# Sidebar Add banner
banner_url:
banner_image:

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url:

# Social links in the site footer
twitter_username:
facebook_username:
googleplus_username:
github_username: "ianding1"
codepen_username:
dribbble_uername:
medium_username:
instagram_username:
pinterest_username:
linkedin_username:
weibo_username:

# http://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: '/blog/page:num/'

plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed

permalink: pretty
markdown: kramdown
